---
title: "Writing Functions"
output: github_document
---

```{r, echo = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d


```


## Z - scores!!

Let's compute the z score version of a list of numbers. 
 - testing incrementally, mean = 0  and variance = 1

```{r}
x_vec = rnorm(25, mean = 7, sd = 4)


(x_vec - mean(x_vec))/ sd(x_vec)
```

Suppose you want to do this often.

```{r, eval = FALSE}
z_scores = function(ARGUMENTS) {
  
  BODY OF FUNCTION
}
```

Here, you are telling function R you have a function X 
- instead of return you could put z
```{r}
z_scores = function(x) {
 z =  (x - mean(x))/sd(x)
 return(z)
}
```

Now you have a z score function

```{r}
z_scores(x = x_vec)
```



